const execData = [
	{
		imgPath: "../paj.jpg",
		name: "Paj Sae Lim",
		description: "CryptoGodPaj",
		role: "Co-President",
		containerID: "exec-member-1",
	},
	{
		imgPath: "../kmao.png",
		name: "Kevin Mao",
		description: "You can call me K Meow",
		role: "Co-President",
		containerID: "exec-member-2",
	},
	{
		imgPath: "../roger.png",
		name: "Roger Chen",
		description: "CryptoGodRoger",
		role: "Co-President",
		containerID: "exec-member-3",
	},
	{
		imgPath: "../avneet.png",
		name: "Avneet Singh",
		description: "CryptoGodAvneet",
		role: "Vice-President",
		containerID: "exec-member-4",
	},
	{
		imgPath: "../eric.jpg",
		name: "Eric Ning",
		description: "I am very smart",
		role: "Vice-President",
		containerID: "exec-member-5",
	},
	{
		imgPath: "../alice.jpg",
		name: "Alice Liao",
		description: "",
		role: "Treasurer",
		containerID: "exec-member-6",
	},
	{
		imgPath: "../james.jpg",
		name: "James Teng",
		description: "",
		role: "Head of Technology",
		containerID: "exec-member-7",
	},
	{
		imgPath: "../eva.png",
		name: "Eva Wu",
		description: "King",
		role: "Secretary",
		containerID: "exec-member-8",
	},
	{
		imgPath: "../desmond.jpg",
		name: "Desmond Ma",
		description: "	",
		role: "Secretary",
		containerID: "exec-member-9",
	},
];

const dirData = [
	{
		imgPath: "../sanjith.jpg",
		name: "Sanjith De Silva",
		description: "",
		role: "Director of Socials",
		containerID: "dir-member-1",
	},
	{
		imgPath: "../eunice.png",
		name: "Eunice Chan",
		description: "",
		role: "Director of Socials",
		containerID: "dir-member-2",
	},
	{
		imgPath: "../kevin.jpg",
		name: "Kevin Bao",
		description: "",
		role: "Director of HR",
		containerID: "dir-member-3",
	},
	{
		imgPath: "../scott.jpg",
		name: "Scott Connally",
		description: "",
		role: "Director of HR",
		containerID: "dir-member-4",
	},
	{
		imgPath: "../nala.png",
		name: "Nala Hong",
		description: "",
		role: "Director of Careers",
		containerID: "dir-member-5",
	},
	{
		imgPath: "../catherine.png",
		name: "Catherine Xie",
		description: "",
		role: "Director of Careers",
		containerID: "dir-member-6",
	},
	{
		imgPath: "../kirat.jpg",
		name: "Kirat Singh",
		description: "",
		role: "Director of Education",
		containerID: "dir-member-7",
	},
	{
		imgPath: "../yuvi.jpg",
		name: "Yuvraj Singh",
		description: "",
		role: "Director of Education",
		containerID: "dir-member-8",
	},
	{
		imgPath: "../alex.jpg",
		name: "Alex Weng",
		description: "",
		role: "Director of Publications",
		containerID: "dir-member-9",
	},
];

const advisorData = [
	{
		imgPath: "../cameron.png",
		name: "Cameron Baker",
		description: "",
		role: "Solidity Developer @ Lyra",
		containerID: "advisor-member-1",
	},
	{
		imgPath: "../zhong.png",
		name: "Zhong Guan",
		description: "",
		role: "Counsel",
		containerID: "advisor-member-2",
	},
	{
		imgPath: "../holmen.png",
		name: "Holmen Tham",
		description: "",
		role: "Technical Advisor",
		containerID: "advisor-member-3",
	},
];
